export const PASSWORD_RESET_CODE_SENT = 'PASSWORD_RESET_CODE_SENT';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const START_LOADING = 'START_LOADING';
export const UPDATE_CODE = 'UPDATE_CODE';
export const START_LOADING_PASSWORD_RESET = 'START_LOADING_PASSWORD_RESET';
export const STOP_LOADING_PASSWORD_RESET = 'STOP_LOADING_PASSWORD_RESET';
